/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as A11yFixesRouteImport } from './routes/a11y-fixes'
import { Route as A11yChecklistRouteImport } from './routes/a11y-checklist'
import { Route as A11yRouteImport } from './routes/a11y'
import { Route as IndexRouteImport } from './routes/index'

const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const A11yFixesRoute = A11yFixesRouteImport.update({
  id: '/a11y-fixes',
  path: '/a11y-fixes',
  getParentRoute: () => rootRouteImport,
} as any)
const A11yChecklistRoute = A11yChecklistRouteImport.update({
  id: '/a11y-checklist',
  path: '/a11y-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const A11yRoute = A11yRouteImport.update({
  id: '/a11y',
  path: '/a11y',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a11y': typeof A11yRoute
  '/a11y-checklist': typeof A11yChecklistRoute
  '/a11y-fixes': typeof A11yFixesRoute
  '/mobile': typeof MobileRoute
  '/offline': typeof OfflineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a11y': typeof A11yRoute
  '/a11y-checklist': typeof A11yChecklistRoute
  '/a11y-fixes': typeof A11yFixesRoute
  '/mobile': typeof MobileRoute
  '/offline': typeof OfflineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a11y': typeof A11yRoute
  '/a11y-checklist': typeof A11yChecklistRoute
  '/a11y-fixes': typeof A11yFixesRoute
  '/mobile': typeof MobileRoute
  '/offline': typeof OfflineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a11y'
    | '/a11y-checklist'
    | '/a11y-fixes'
    | '/mobile'
    | '/offline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a11y' | '/a11y-checklist' | '/a11y-fixes' | '/mobile' | '/offline'
  id:
    | '__root__'
    | '/'
    | '/a11y'
    | '/a11y-checklist'
    | '/a11y-fixes'
    | '/mobile'
    | '/offline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  A11yRoute: typeof A11yRoute
  A11yChecklistRoute: typeof A11yChecklistRoute
  A11yFixesRoute: typeof A11yFixesRoute
  MobileRoute: typeof MobileRoute
  OfflineRoute: typeof OfflineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a11y-fixes': {
      id: '/a11y-fixes'
      path: '/a11y-fixes'
      fullPath: '/a11y-fixes'
      preLoaderRoute: typeof A11yFixesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a11y-checklist': {
      id: '/a11y-checklist'
      path: '/a11y-checklist'
      fullPath: '/a11y-checklist'
      preLoaderRoute: typeof A11yChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a11y': {
      id: '/a11y'
      path: '/a11y'
      fullPath: '/a11y'
      preLoaderRoute: typeof A11yRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  A11yRoute: A11yRoute,
  A11yChecklistRoute: A11yChecklistRoute,
  A11yFixesRoute: A11yFixesRoute,
  MobileRoute: MobileRoute,
  OfflineRoute: OfflineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
